### ISSUE TITLE
Can't select last track in SetModeVisualTrack

### ISSUE THREAD

**Issue by elgiovanno** [gwatcha/reaper-keys#12]
When selecting tracks in Visual Track Mode via [ V, j ] or [ V, G ] the last track is not being selected no matter where the starting point of your track selection is. I'm able to select the last track only by reaching it with [ j ] and [G] in Normal Mode or with the mouse. This does not replicate itself with the first track if you try to duplicate this in reverse order with [ V, gg ] or [ V, k ].

**Comment by gwatcha** [comment]
Should be fixed in v1.3.0 . Thanks for pointing it out!

**Comment by elgiovanno** [comment]
Confirmed fix!
