### ISSUE TITLE
did you remove the deselect/clearselection events kb?

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#13]
I think it was "S" before.

**Comment by gwatcha** [comment]
I moved it to 'ESC' and made S select items under the cursor.

**Comment by molleweide** [comment]
Smart!

**Comment by molleweide** [comment]
I have to go throught the internals more because it is still a bit hard for me to understand how the different action types go together.

**Comment by gwatcha** [comment]
Thanks!
