### ISSUE TITLE
MacOS: focusing status/command window interrupts state

### ISSUE THREAD

**Issue by elgiovanno** [gwatcha/reaper-keys#16]
Not sure if there's a way around this as it's standard Reaper behavior(maybe??). But just in case.

Interruption happens in all modes. ESC will close the focused command window and clear the RK state. You can only get back to previous state by clicking "Clear" in the command window or somewhere that won't affect where you left off(transport and tool bar area). Very few exceptions exist. So far I've only found that in Visual Mode h and l and their variants continue to work with varying degrees of consistency.

EDIT: should say that ESC on focused RK window closes the window and _suspends_ state, not clear it. If you continue what you were doing after focusing the rk window and escaping or clicking out of focus, state resumes as it was.

**Comment by gwatcha** [comment]
If you click on the main window and leave the RK window unselected, does it still interrupt?

**Comment by elgiovanno** [comment]
@gwatcha hi! Assuming that you mean clicking the main _after_ having focused rk window? In this case clicking focus back to the main window allows state to continue where it left off. I edited my last comment because escaping rk window from focus also returns you to the state you had before interruption. So I suppose the issue becomes a question of can state continue independent of whether the rk window is focused or unfocused?

**Comment by gwatcha** [comment]
>  So I suppose the issue becomes a question of can state continue independent of rk window focus state?

Unfortunately no, when the message window is focused, no key presses are sent to the scripts.
The intended way to use the window is to leave it on the side and have the main window focused. If you want to get rid of it though, there's an option that will be released soon called 'log_level' that can turn off the messages.

**Comment by gwatcha** [comment]
FocusMain is used with FX plugins

**Comment by gwatcha** [comment]
t
