### ISSUE TITLE
Track color undo

### ISSUE THREAD

**Issue by elgiovanno** [gwatcha/reaper-keys#17]
If you color a track or tracks via RK or mouse it it gets undone by the next undo action even after performing one or several actions after having colored the track(s). Example: color a track then delete a few items. Undo the last deleted item and it will also undo the track color. The remaining undo history behaves appropriately.

**Comment by gwatcha** [comment]
Hmm I can't reproduce this one. Maybe it's a mac specific problem? Did you notice any other actions that behave like this?

**Comment by elgiovanno** [comment]
I did not. I'm gonna try a couple more things and report back.

**Comment by elgiovanno** [comment]
Went deeper. Narrowed it down to tracks that are auto-colored with a gradient in SWS. Confirmed this behavior in a RK-free environment. Closing this issue as it is default SWS behavior.

**Comment by gwatcha** [comment]
Ah I see, okay!
