### ISSUE TITLE
Call set midi grid commads in script doesn't seem to work.

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#18]
When running set MIDI grid actions from the actions list view then it works, but
running the commands from reaper-keys script doesn't seem to work.

**Comment by gwatcha** [comment]
I think this works now. Just make sure you don't have the option 
`  ["g"] = "ToggleMidiEditorUsesMainGridDivision"`
set

**Comment by molleweide** [comment]
Oh I tried the option and it works. It has to be fixed a little bit.
It seems you have to run the toggle command twice afterwards for the change to take effect.
change > toggleOff > toggleOn.

I have another question also. When I try to insert a note to the right (l) it skips
the first grid step and inserts the note from the second step? Do you know what I mean?
I want to insert for each grid step.

**Comment by gwatcha** [comment]
I see the insert note problem, I didn't realize inserting also moved the edit cursor. I fixed it now.
