### ISSUE TITLE
Error when deleting all selected files

### ISSUE THREAD

**Issue by elgiovanno** [gwatcha/reaper-keys#19]
main.lua:67: bad argument #1 to SetOnlyTrackSelected (MediaTrack expected)

This error does not happen when deleting all tracks via "d,i,g". Only with "V,i,g" + bkspc, or "V, G" from 1st track + bkspc.

**Comment by elgiovanno** [comment]
Just tested this from the develop branch and it is a non-issue there.

Returning to master(no merge) caused errors for me though. Is switching branches for testing seamless or are other actions required?

**Comment by elgiovanno** [comment]
Oh I just saw your commit that fixes this. Teehee!!!

**Comment by gwatcha** [comment]
Yep! I'll make a new release on master soon, there's just some other bugs right now.
