### ISSUE TITLE
Could not read state data when trying to select track/timeline

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#20]
Using 'develop' branch.
e822474a18ec8ace1391cfbf6b345f0e3d83c141

Keys[ERROR]: Could not read state data from file, it may have become corrupted. Resetting.
Keys[ERROR]: Could not read state data from file, it may have become corrupted. Resetting.

I get this error when I enter either visuai or track selection witn v/V.
I am not sure what this means.

Btw, should I link to last commit every time I make an issue, or is it always
implied that we are refering to the develop branch latest if no SHA is referenced?

**Comment by molleweide** [comment]
I notice that the state log isn't showing either.

This is what my state file looks like:

```
{
  context = "main",
  key_sequence = "",
  last_command = {
    action_keys = {
      "Reset"
    },
    action_values = {
      {
        "Stop",
        "SetModeNormal",
        "SetRecordModeNormal",
        "ResetSelection"
      }
    },
    context = "main",
    mode = "normal",
    sequence = {
      "command"
    }
  },
  last_searched_track_name = "^$",
  last_track_name_search_direction_was_forward = true,
  macro_commands = {},
  macro_recording = false,
  macro_register = "+",
  mode = "normal",
  timeline_selection_side = "left",
  visual_track_pivot_i = 0
}
```

**Comment by molleweide** [comment]
This is what my state looks like when hitting "V"
{
context = "main",
key_sequence = "",
last_command = {
action_keys = {
"SetModeVisualTrack"
},
action_values = {
((loadstring or load)("\27LuaS\0\25\13\n\26\n\4\8\4\8\8xV\0\0\0\0\0\0\0\0\0\0\0(w@\2M@/Applications/REAPER App/Scripts/./reaper-keys/internal/library/library.lua\15\0\0\0\23\0\0\0\0\0\4\20\0\0\0\6\0@\0\7@@\0$\0F\0@\0GÀ\0\0\0\0d@\0\1F\0@\0GÀÀ\0\0\0\0Á\0\1\0d\1N@Á\0Á\0ÁÀ\1\0¤@\0\1\0Â\0À\0\0¤@\0\1&\0\0\9\0\0\0\4\7reaper\4\20GetLastTouchedTrack\4\21SetOnlyTrackSelected\4\24GetMediaTrackInfo_Value\4\15IP_TRACKNUMBER\19\1\0\0\0\0\0\0\0\4\8setMode\4\13visual_track\4\25setVisualTrackPivotIndex\2\0\0\0\0\0\1\0\0\0\0\0\20\0\0\0\16\0\0\0\16\0\0\0\16\0\0\0\17\0\0\0\17\0\0\0\17\0\0\0\17\0\0\0\19\0\0\0\19\0\0\0\19\0\0\0\19\0\0\0\19\0\0\0\19\0\0\0\21\0\0\0\21\0\0\0\21\0\0\0\22\0\0\0\22\0\0\0\22\0\0\0\23\0\0\0\2\0\0\0\14current_track\3\0\0\0\20\0\0\0\21visual_track_pivot_i\13\0\0\0\20\0\0\0\2\0\0\0\5_ENV\16state_interface",'@serialized'))
    },
    context = "main",
    mode = "normal",
    sequence = {
      "command"
    }
  },
  last_searched_track_name = "^$",
last_track_name_search_direction_was_forward = true,
macro_commands = {},
macro_recording = false,
macro_register = "+",
mode = "visual_track",
timeline_selection_side = "left",
visual_track_pivot_i = 64.0
}

**Comment by gwatcha** [comment]
Yeah link the commit, the develop branch is changing frequently.

**Comment by molleweide** [comment]
I updated with the commit.

**Comment by gwatcha** [comment]
Not really, but I'm not too much of an authority on git conventions.

**Comment by gwatcha** [comment]
If you want to work on something without a bugged version of reaper keys I actually recommend using the master branch now xD. Though you testing out latest commits in develop is actually very useful.

**Comment by gwatcha** [comment]
So it's up to you I'm saying.

**Comment by molleweide** [comment]
> Not really, but I'm not too much of an authority on git conventions.
Allright cool.

> If you want to work on something without a bugged version of reaper keys I actually recommend using the master branch now xD. Though you testing out latest commits in develop is actually very useful.
I will jump between master and dev then. I'd like to help as much as possible.
Tell me also if there is anything you want me to look into.

**Comment by gwatcha** [comment]
Thanks for the help! 

It would help to know that on the develop branch, there is a setting 'log level' in definitions/config.lua
If you set that to 'trace', reaper-keys provides the most amount of info for debugging

**Comment by molleweide** [comment]
Nice! I'll use trace from now on.

**Comment by gwatcha** [comment]
Also it works now with 961bc46
