### ISSUE TITLE
reg macro err / latest dev

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#23]
fd21a0c4745252c7554de44f84cff75555c4a6fe
![Screenshot 2020-05-30 at 09 39 19](https://user-images.githubusercontent.com/5650722/83322658-dce4e980-a259-11ea-956f-7008d870c9c1.png)

**Comment by molleweide** [comment]
Which file is it that I have to delete/reset in order for the error to go away?

**Comment by gwatcha** [comment]
Oh no, hmm. Try deleting the `saved/macros.lua` file

**Comment by molleweide** [comment]
no such file. only saved.lua

**Comment by gwatcha** [comment]
Ah that may be it. Try to create an empty saved/macros.lua file for now then

**Comment by gwatcha** [comment]
Try creating the directory saved/data

**Comment by gwatcha** [comment]
Alright I fixed it in the latest commit to master.
