### ISSUE TITLE
Item selection behavior

### ISSUE THREAD

**Issue by elgiovanno** [gwatcha/reaper-keys#24]
Hi! Don't have much time so I'll be quick. Example scenario:

There are two items in a track with no space between them. Navigating to the second item start with 'w' and then selecting with 's,i,w' or 'v,i,w' selects the previous item instead, as if we had navigated to the end of the first item with 'e' and then ran the selection actions. When there is separation between the two items, this is not an issue.

**Comment by gwatcha** [comment]
This is reapers behaviour for selecting the item nearest the edit cursor so this is intended. Just do 'se' to select the other item.

**Comment by gwatcha** [comment]
You know what, I'll actually work on changing this because it may be annoying.

**Comment by gwatcha** [comment]
Here you go 782fec1 fix: change select inner item to prioritize later items

**Comment by elgiovanno** [comment]
Hey! Cool I'll have a look tomorrow night as I'm away from a computer until then. Will report back as soon as I test it out!
