### ISSUE TITLE
MacOS: Strange Insert Marker behavior

### ISSUE THREAD

**Issue by elgiovanno** [gwatcha/reaper-keys#26]
There is strange behavior around entering markers. I haven't been able to find a distinct pattern for the issue, but here's an example of a sequence of marker entries that I just did and how it behaved.

Move from project start to bar 2 and "m, a" to enter first marker. Marker inserted with name "a" and id 1. All is well there.

Move to bar 3 and "m, s". Marker is inserted with name "s" but ID 4.

Move to bar 4 and "m, d". Marker is inserted with name "d" but ID 6.

Move to bar 5 and "m, f". Marker is inserted with name "f" but ID 3.

Move to bar 6 and "m, z". Marker is inserted with name "z" but ID 5.

Move to bar 7 and "m, g". Marker is inserted with name "g" but ID 0 AND marker a/1 is removed from the marker list/lane.

I saw a commit for changes to the marks system. Is this related to that? Can someone replicate this?

**Comment by gwatcha** [comment]
Yeah this is a bug, give me a day or two to fix it.

**Comment by elgiovanno** [comment]
Hmmm... I casually opened a brand new project to test the RK workflow from scratch and when I got to markers, they were created perfectly with no ID issues or vanishing markers.

**Comment by elgiovanno** [comment]
Also, yeah dude, no rush. I know this is project has been a lot of work for you and it's not like your getting paid to do it. Whenever it's done, it's done :). I'm getting into the code slowly studying it's overall structure first as I'm quite rusty. But I'm hoping to be able to submit pull requests for fixes/approved features in the future. For now, I post these issues as I find them so as to not forget about them later.

**Comment by elgiovanno** [comment]
Some markers also won't delete with <C-'> -> mark. looking for patterns.

**Comment by gwatcha** [comment]
Should be fixed on latest!

**Comment by elgiovanno** [comment]
This issue is persisting on my end :/

**Comment by gwatcha** [comment]
Okay I'll look into it more tomorrow.

**Comment by gwatcha** [comment]
Alright I figured it out! Check out the latest master or develop. I can't manage to break it anymore, but if you find a sequence that breaks it please let me know! I also added a new key '~' to recall regions, so to not conflict with track selections.

**Comment by elgiovanno** [comment]
Hey! It's definitely working better now. But there are still some holes in behavior. I still haven't been able to find a specific pattern, and before I try to dig deeper I thought I'd ask if you could give me a synopsis of how your marks system works? I know that markers are based on the edit cursor and regions on a timeline selection. Those I can see in the region/marker manager. Not sure about track selection marks though? How do those get stored/recalled? Is there a way to delete all marks in one go? In testing, I'm unsure if maybe I've set a mark on a track selection by mistake. Maybe a config to log all current marks for debugging? 

I'll do another comment with any findings that I can establish repetition on :)

**Comment by elgiovanno** [comment]
nevermind

  local _, all_project_marks = project_io.getAll('marks')
  log.trace("New Marks State: " .. format.block(all_project_marks))

**Comment by gwatcha** [comment]
Oops sorry I didin't see this comment until now. Is it okay now? 

Markers work like this:

` -> recalls edit cursor position
' -> recalls selected tracks
~ -> recalls region

In any mode, the 'm' key will store a mark which will save the current track selection, time selection, and edit cursor position.

If you are in visual mode, the mark also creates a visible region.
If you  are in normal mode, the mark also creates a visible marker.
If you are in visual track mode, the mark does not create anything apart from the mark.

There is no way to delete all marks in one go.

**Comment by elgiovanno** [comment]
Gotcha! I'll take a deeper dive tonight.

**Comment by gwatcha** [comment]
Check out the docs for marks btw: https://gwatcha.github.io/reaper-keys/marks.html

**Comment by elgiovanno** [comment]
1.9.0 is an epic release!

**Comment by gwatcha** [comment]
Thanks! It wasn't too hard to sort the actions

**Comment by gwatcha** [comment]
Let me know what you guys think about the new documentation too, feel free to contribute anything as well.
