### ISSUE TITLE
MacOS error in Visual Track Mode

### ISSUE THREAD

**Issue by elgiovanno** [gwatcha/reaper-keys#27]
utils.lua:208: bad argument #2 to 'GetTrack' (number expected, got nil)

Getting this error when deleting tracks in VTM. The only two patterns I've been able to replicate consistently are deleting all tracks and deleting a selection of more than one track that includes the last track or the track before last. I've found  the issue in other instances but those were less consistent in reproduction.

**Comment by gwatcha** [comment]
should be fixed now on develop!
