### ISSUE TITLE
Requesting permission to submit pull request

### ISSUE THREAD

**Issue by elgiovanno** [gwatcha/reaper-keys#28]
Hi! I created a feature branch off of develop that adds a simple action for splitting item(s) at the edit cursor on selected tracks. I'd like to submit it for review but can't push my branch due to lack of permissions.

**Comment by molleweide** [comment]
Hmm, I can do it without any problems.

**Comment by gwatcha** [comment]
You don't have to push your branch to create a merge request, take a look at molleweides example: https://github.com/gwatcha/reaper-keys/pull/15

Note the 'gwatcha:master from molleweide:feature-change-volume-and-pan'

**Comment by elgiovanno** [comment]
@gwatcha Ah I see. He's requesting a merge from his fork to your repo. I cloned yours down and created my branch off of the latest develop and thought I'd be able to --set-upstream on that for the pull request. I'll clone my fork, add my branch/changes and delete and try again. Thanks!

**Comment by elgiovanno** [comment]
@gwatcha Sorry to be a pain about this, but could you describe your ideal git workflow for contributions. some of this is new to me. Is it basically just fork and branch off of develop for fixes/features and pull request from that? Any specific naming conventions you'd prefer?

**Comment by gwatcha** [comment]
Yes it's that! Make a new branch starting at develop and submit a merge request for the develop branch. For naming conventions, I have an auto release system in place that detects any commits starting with 'fix:', 'perf:' or 'feat:', and adds the message into the release notes for the next release on master. So if you like, prefix any feature commits with 'feat:', fixes with 'fix:', and performance updates with 'perf:'

**Comment by molleweide** [comment]
Sorry @elgiovanno, I misunderstood you in my previous comment.
I recently read this article which was quite nice about branching workflows, since
I am also a bit of a beginner when it comes to open source contributing.
https://nvie.com/posts/a-successful-git-branching-model/

**Comment by elgiovanno** [comment]
It's been 10 years since Git Flow??!!! Wow that makes me feel old. Thanks for the link. I am familiar with it but it's been a while since I code and it's been a good refresher. I think that thing that trips me up is merging from a fork. That is totally new to me. Have always worked directly from the repository with a branching system and pushed branches for requests. This is new and cool though!

**Comment by elgiovanno** [comment]
https://www.gun.io/blog/how-to-github-fork-branch-and-pull-request

I think this pretty much nails what I need to do :)

**Comment by gwatcha** [comment]
Great, I saw you made 2 pull requests, so I'll close this!

**Comment by elgiovanno** [comment]
I know this is closed, but I have a quick question about fork/upstream. It seems I can only fetch/merge upstream/master? I thought setting an upstream would make a remote of all the repos branches. Basically did this but I merge instead of rebase:

https://stackoverflow.com/a/7244456

But doing that for develop won't work for me. I did a pull request on my fork:develop to sync up to @gwatcha last time.

**Comment by molleweide** [comment]
`git fetch upstream --all` (i thihk) or `git fetch upstream brach`

**Comment by elgiovanno** [comment]
The second one seemed to do something, but got merge upstream/develop returns "not something we can merge". I'll have a look later when I'm back at my computer. Thanks!

**Comment by molleweide** [comment]
I think you should ’checkout’ upstream develop and then make a new local branch for working on.

**Comment by elgiovanno** [comment]
Thanks for that @molleweide. This is what ended up working for me:

https://stackoverflow.com/a/15731197

git remote add --track develop upstream-develop git@github.com:gwatcha/reaper-keys.git
git pull upstream-develop develop

Quite verbose and explicit, but all else failed. At one point I started thinking about deleting my fork and starting over, but it looks like I may not have to. Thank you for the help!

**Comment by elgiovanno** [comment]
What my git branches look like now. Let me know if anything looks weird to you guys.

$ git br -a
* develop
  feat-add-config-visual-track-timeline-movement
  feat-add-split-at-edit-cursor
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/completions-based
  remotes/origin/develop
  remotes/origin/feat-add-config-visual-track-timeline-movement
  remotes/origin/feat-add-split-at-edit-cursor
  remotes/origin/key-binding-improvements
  remotes/origin/master
  remotes/upstream-develop/develop
  remotes/upstream/master

**Comment by gwatcha** [comment]
I think so
