### ISSUE TITLE
midi `Vds` deletes all notes at cursor including not selected notes

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#39]
"Vds" should only delete the selected notes right? 
in the image below all notes in horizontally adjacent to selection are deleted.
![Screen Shot 2020-09-09 at 6 46 48 PM](https://user-images.githubusercontent.com/5650722/92628381-01c31100-f2cd-11ea-9bad-0cd4952642c2.png)

**Comment by gwatcha** [comment]
Ah, I named that command 'SelectedNotes', but it's actually a timeline selector type, so it means to set the timeline selection to the selected notes. That's why it is deleting the notes underneath as well. To delete just the selected notes, use 'D'

**Comment by molleweide** [comment]
Ohh thanks!!

**Comment by molleweide** [comment]
Dude i fucking love reaper key

**Comment by molleweide** [comment]
i would sell my whole family for it

**Comment by gwatcha** [comment]
ahaha thanks

**Comment by molleweide** [comment]
Hey Mike, can I ask you if you know if there is a way one can export and import midi tracks (.mid) in reascript?

**Comment by molleweide** [comment]
I’ve done a little bit of research and it doesn’t seem that hard to just write two functions for writing and recalling midi so i am going to try to implement this.
