### ISSUE TITLE
Capital letters not working on MacOS.

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#4]
Capital letters are not being registered for me - they register as small letters.
I'll get back if I find a solution.

**Comment by gwatcha** [comment]
Thanks for letting me know.

I think I may know the issue, but do you mind posting what REAPER thinks these letters are by exporting a keymap line with a bound capital letter? To do that, just go into the action list, bind a random action to a capital letter, select the line and chose export selected items at the bottom left. Then just past the contents of the file.

**Comment by molleweide** [comment]
Allright, I will try that and get back.

I also noticed that I got this message in the terminal:
`warning: the following paths have collided (e.g. case-sensitive paths on a case-insensitive filesystem) and only one from the same colliding group is in the working tree:`

**Comment by molleweide** [comment]
so I think that only the lowercase keys got generated.

**Comment by molleweide** [comment]
I bound the Q key.

`SCR 4 0 RS78877989c2a870c271626cd00b4b2ef167e896ac "Custom: Add project markers as cue points to selected items and replace source files.lua" "ReaTeam Scripts/Items Editing/Add project markers as cue points to selected items and replace source files.lua" KEY 5 81 \_RS78877989c2a870c271626cd00b4b2ef167e896ac 0`

**Comment by gwatcha** [comment]
Thanks for doing that! This turns out to be the same problem as this one https://github.com/gwatcha/reaper-keys/issues/3

I've pushed a fix to make the paths case insensitive, so it should detect the capital letters now.

**Comment by molleweide** [comment]
Good news and bad news.
Capital letters work, however it seems as if lower case letters aren't working now.
I seem to be able to do everything except lower case.

It sais:
Can't load file:

./reaper-keys/key_scripts/main_j.lua

**Comment by molleweide** [comment]
Now uppercase letters work!!

Before I pulled the changes I removed all the files in the `key_scripts` folder and
now none of the lowercase letters files can be found.
How do I re-download these files?

**Comment by molleweide** [comment]
when run `git checkout upstream/master` then I can see the lowercase letter files
bet when I checkout my own master and then git pull upstream master, then the
lowercase files don't show.

**Comment by gwatcha** [comment]
You'll want to type `git reset --hard HEAD`. Git sees your removal of the files as progress. This command reverts any alterations you made to the repository, and reverts it to the commit and branch you are currently on, which in your case is now `upstream/master`.

**Comment by molleweide** [comment]
Nice!! Thanks a lot!

**Comment by gwatcha** [comment]
No problem!
