### ISSUE TITLE
bug: cross writing btw marks and regions

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#45]
I experience cross writing between marks and regions. I have to look into it further because I looked at it a couple days ago but there is definitely something there because marks and regions dissapear and seem to affect each other in a manner which I cannot deduce right now.

Are you guys also experiencing this?

**Comment by gwatcha** [comment]
Yes I actually wrote it that way intentionally so there is no ambiguous 'GoToMark' commands

**Comment by molleweide** [comment]
Cool, thanks for clarifying!
