### ISSUE TITLE
possible commands gui dissappeared

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#46]
The window showing each possible command has disappeared for me. It happened after I got an error via
an action from another lua project that I am working on. 

I will get back with more info if I find something. I don't know what is the problem atm.

**Comment by gwatcha** [comment]
Hm I am not sure, resetting the state files may help, or trying to open it by pressing different keys.

**Comment by molleweide** [comment]
it came back LOL

**Comment by molleweide** [comment]
victory!!!
