### ISSUE TITLE
getSet_loopTimeRange returns zero for me??

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#47]
I am trying to build a set of custom commands for repeating time sel by inserting new space and then duplicating items.
GetSet looptime returns nothing for me which is what I am trying to investigate atm.

why is it not working in my command but it logs values when I put logs inside your action sequences functions?

```lua
function custom_actions.repeatShiftAllItemsInTimeSelectionByTrackByTimeSel()
  local start_sel, end_sel = reaper.GetSet_LoopTimeRange(0, 0, 0, 0, 0)
  log.user(end_sel) -- <<<<< logs nothing here

  local data = {}
  if reaper.CountSelectedMediaItems(0) < 1 then return end
  data = collectMediaItemData(data)
  DuplicateItems(data, end_sel - start_sel)
end

```

**Comment by molleweide** [comment]
this hopefully makes it more clear what I am trying to achieve.

## section management / @ edit cursor

`necessary commands for fast shuffle around project segments`

- insert space
- paste time sel
- insert space AND paste time sel

this should be 3 different commands for all possible scenarios.

eg.
1. mark go region select
2. copy insert time sel wherever you are..

**Comment by molleweide** [comment]
later i have to figure out what types of actions these could be. eg. i am a bit unsure of how to add a count so you could say `repeat insert time sel x number of times at edit cursor` but i'll figure that out.

**Comment by gwatcha** [comment]
I am not sure, I would make sure the function is being called in the first place.

**Comment by molleweide** [comment]
yeah I am going to do that more thouroghly! I am obviously doing something wrong lol

**Comment by gwatcha** [comment]
Okay sounds good!
