### ISSUE TITLE
trying to make command save all tracks as temp. Visual selection problem.

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#48]
trying to create a command for selecting all tracks and saving them to a template like this.

```lua
-- definitions/actions.lua
  SaveAllTracksAsTemplate = {
    "Reset",
    "FirstTrack",
    "SetModeVisualTrack",
    "LastTrack", -- I lose visual here it seems.
    "SaveTrackTempFromSelected" -- only last track is saved
  }

```

I notice that all tracks aren't being selected.  I need to manually do eg. "NextTrack" for the 
track selection to "occur". 
I'll get back if I solve the problem.

**Comment by gwatcha** [comment]
Use the Reaper "Track: Select all tracks" `40296` action instead.
