### ISSUE TITLE
How would one use the built virtual keyboard?

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#49]
Hey guys,

I am thinking about how one could use the built in virtual midi keyboard when using a laptop.
If you have any ideas please tell me? I'll get back if I come up with something.

**Comment by gwatcha** [comment]
I'm not sure how

**Comment by molleweide** [comment]
Yeah! The first time that I did the searching for it I did not understand enough to understand if I "had" found something but now I think I begin to understand. I'll add to next pr.

**Comment by molleweide** [comment]
I have also implemented a first version of my method for creating sends. I have to learn a little bit more about bitwise operations in order to make it better. I found a script called n0ne fast FX finer that impplements sort of like a fuzzy finder
for adding FX to tracks. It would be kind of ideal to fork that project and that kind of fuzzy finder functionality into reaper keys and then make it so that you can get a fuzzy search for DESTINATION tracks when creating routes. This way it would probably be easy and super fast to create and manage sends with key commands.

**Comment by gwatcha** [comment]
Okay so I won't be able to spend too much time helping you out with the features you are implementing, but if you finish it and create a PR that is mergeable with the master branch, I will review it

**Comment by molleweide** [comment]
No worries. It’s just nice to chat a little. I want to build this stuff myself so that i learn!!
But i think that u r gonna like my additions. It’s going to take me a little while to finish everything but i am starting to see the light

**Comment by molleweide** [comment]
i am putting together a big pr atm. l now understand why it wasn't mergable last time.
i'll submit soon. i am super excited. i hope u will like!!!

**Comment by molleweide** [comment]
i try to build a virtual keyboard mode in my latest pr

**Comment by molleweide** [comment]
Hey I just realized wouldn't the easiest thing be to disable reaper keys so that you can just let
the vkb recieve notes? Does that seem like an easy task Mike? I am going to look into this.
