### ISSUE TITLE
split default bindings into smaller files?

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#50]
the key bindings files are getting quite big like global.lua.
would it make sense to split it into smaller files, eg. global_timeline.lua, global_commands.lua.
what do you think

**Comment by gwatcha** [comment]
I think it's alright as it is!

To be honest, I think the most pertinent issue for this repository is some of the usability concerns with the auto-complete window. Some things to investigate are:
* Is there a way to de-focus the window automatically if it gains focus?
* A pop-up dialog could appear after the first keypress which gives basic instructions to starter users, with an option to hide it forever. It would say something like: 'Welcome to Reaper Keys! Start using by defocusing the autocomplete window, and typing some keys. To get you started, press <M-x> (Alt+X) to pull up a list of bindings that you can filter. Your first quest is to learn the timeline_operators, as these are the most used - so set the binding list to only display all the timeline_operators and try them out one by one! If a 'script is running in the background' dialog pop's up, just select 'new instance' and 'remember'. Check out the 'definitions' directory in the Reaper-Keys folder to customize Reaper Keys. I hope you make some great music!'

If you are looking for ways to help (much appreciated btw), those two issues would have the most impact on users I believe.

**Comment by molleweide** [comment]
I agree. Those are important features. 
I haven’t had time to dive into gui and windws so much. But looking fwd to it.
