### ISSUE TITLE
Feedback window keeps moving left

### ISSUE THREAD

**Issue by sadguitarius** [gwatcha/reaper-keys#51]
Hello, I'm having an issue where the feedback window keeps moving left by a few pixels every time it is redrawn. This only happens if the time threshold is reached for the window to show options after a key press. I'm using the i3 window manager on Linux, which doesn't always play well with floating windows and I'm sure is a pretty specific use case, but other Reaper floating windows seem to be doing ok. Any ideas? Thank you and I'm terribly excited about this project!

**Comment by gwatcha** [comment]
Hey thanks for the excitement for the project! Unfortunately I'm not sure how to help with this. I am using Manjaro with Plasma and it is not shifting, so I think it has to do with i3.
