### ISSUE TITLE
How to add notes to piano roll

### ISSUE THREAD

**Issue by 0atman** [gwatcha/reaper-keys#54]
Hi @gwatcha, reaper-keys is revolutionizing my life, both editing [podcasts](https://www.youtube.com/watch?v=p3bDE9kszMc&list=PL95NP4bDITAln7fq-cCqzOFE15UvVthuL) and (soon hopefully) creating music.
THANK YOU!

I don't know how to add notes in the piano roll, however.

I can copy and paste with `y` and `p` motions, and move between them with `w` and `b` and `h` and `l`, but when I'm in the right spot, what's the workflow for creating notes?

I feel like it's something around `a`, but none of the which-key prompts really clues me in. I can make notes seemingly randomly with some, but I feel like there's some core knowledge I'm missing.

How do you use the piano roll? Thank you so much!

**Comment by molleweide** [comment]
Yo, rk is not really built for managing notes in the piano roll in its current state. iirc G told me a while ago that he had put together the piano roll actions quite fast.
With time we could put together more commands for the piano roll, which is my intention, but not much yet.

**Comment by AntoineBalaine** [comment]
@0atman I have [this commit](https://github.com/AntoineBalaine/reaper-keys/commit/4501870ee85965f76015a9dc2cb85bee38b411aa) that might help with what you're looking for: I added actions for inserting notes and manœuvering them in the midi editor. Hope this helps!

**Comment by 0atman** [comment]
oh incredible! I'll try it out!

**Comment by AnthonyBalaine** [comment]
> I'll try it out!

I welcome any feedback ;)

**Comment by myrrc** [comment]
Yeah, that seems like a bug. Fixed that in 2.0.0-a2.
Notes can be inserted by using `a` in midi editor. Sample workflow follows:
```
o # create new track
im # insert midi item
<Space>so # open in midi editor
a # add a note
```

**Comment by 0atman** [comment]
> Yeah, that seems like a bug. Fixed that in 2.0.0-a2. Notes can be inserted by using `a` in midi editor. Sample workflow follows:
> 
> ```
> o # create new track
> im # insert midi item
> <Space>so # open in midi editor
> a # add a note
> ```

It works! Thank you very much! (2.0 is AMAZING btw)

I should look these up in the config, but how do you set the length of the midi note added with `a`?

![image](https://github.com/gwatcha/reaper-keys/assets/114097/4e61c664-8f4b-4c4b-b87d-514a096b8684)

**Comment by myrrc** [comment]
Strangely, there is no binding for that currently. I'll have a look.

**Comment by 0atman** [comment]
thank you! perhaps it should be similar in mnemonic to setting length of an audio clip (which I also don't know!)
