### ISSUE TITLE
Wrong key inputs on keyboard layouts other than qwerty

### ISSUE THREAD

**Issue by AntoineBalaine** [gwatcha/reaper-keys#55]
Hello,

I use a keyboard layout other than qwerty, and the numbers row doesn't get picked up correctly. 
Also, it doesn't pick up capital letters either. 
I'm on MacOs, can probably test on my linux machine as well. 

Here's what happens with the numbers row:
If I hit where the `<S-1>` is on a qwerty, I see the qwerty's `<S-1>` output - even though the OS is using a different layout.
If I hit `<S-h>`, it just hits `<h>`.

Is there a way around this issue?

**update**: on my linux, the problem is the same: the shift keys doesn't get picked up correctly. I'd say that's where the problem is coming from.

**Comment by AntoineBalaine** [comment]
Found It! 
Dunno if reaper's the culprit upon importing, all the lowercase keys had a duplicate keybinding that included the shift+[key]. 
![reaper-keys](https://github.com/gwatcha/reaper-keys/assets/54488126/9ef46713-3be7-4795-a0fb-53d3baab5546)

**Comment by deetuned** [comment]
> Found It! Dunno if reaper's the culprit upon importing, all the lowercase keys had a duplicate keybinding that included the shift+[key]. ![reaper-keys](https://user-images.githubusercontent.com/54488126/244536381-9ef46713-3be7-4795-a0fb-53d3baab5546.png)

Hi, @AntoineBalaine. May I ask how exactly you went about adjusting every keybind? Did you do it manually?

Cheers

**Comment by molleweide** [comment]
> I'm on MacOs, can probably test on my linux machine as well.

hmm, i have noticed this on my m1 macbook as well. however, this wasn't an issue before for me on intel macs.

**Comment by molleweide** [comment]
> Found It! Dunno if reaper's the culprit upon importing, all the lowercase keys had a duplicate keybinding that included the shift+[key]. ![reaper-keys](https://user-images.githubusercontent.com/54488126/244536381-9ef46713-3be7-4795-a0fb-53d3baab5546.png)

aaah oh wait you solved hmm i have to check this out later myself

**Comment by molleweide** [comment]
also, great to see some ppl in this repo

**Comment by AntoineBalaine** [comment]
@deetuned Yes, I updated every key bind manually - both in TCP actions list, and in midi editor's list.

> does it reload keys again with the faulty duplicate shift keys?
@molleweide  yes, it does. 
I'm working on a fork - reaper-keys is sooo great, I've been loving every minute with it.

**Comment by molleweide** [comment]
> > it fore sure, is a recent problem because everything has worked flawlessly before
> > dunno… Latest reaper's fault, or my system's fault, maybe…?

yeah im starting to think that it might have something to do with the latest reaper versions for sure.

**Comment by molleweide** [comment]
> I'm working on a fork - reaper-keys is sooo great, I've been loving every minute with it.

awesome! what kind of music do you use rk for?

**Comment by AntoineBalaine** [comment]
I want to do some electronic stuff, but I'm still in the midst of getting comfortable with it.

**Comment by molleweide** [comment]
anything from classical composing to hardstyle lol. im down for chatting about rk anytime!

**Comment by AntoineBalaine** [comment]
Very good, let's do it! My email's in [my branche's](https://github.com/AntoineBalaine/reaper-keys/tree/map_cleanUp) `git log`. Let's set a time and chat!
Cheers

**Comment by molleweide** [comment]
I submitted a forum post for this. @AntoineBalaine please tell me if Im missing something in the post that should be included.

https://forum.cockos.com/showthread.php?p=2688754#post2688754

**Comment by molleweide** [comment]
I also posted the forum question into Chat GPT without any real results other than it thinking that there could have been some change to how reaper treats assigning command IDs to upper case key combinations.

**Comment by AntoineBalaine** [comment]
Dunno… I saw your posts, thanks for looking into the topic. 

I have an updated keymap on [my mapCleanUp branch](https://github.com/AntoineBalaine/reaper-keys/tree/map_cleanUp) , maybe we can see if it's worth merging it and call it a day - and I mean merging only the keymap changes. Would you be able to give it a try and see if it's working first, though?

This might be a linux-only issue, or because I don't use a qwerty layout, or whatever. I don't know if it's worth running in circles about: most users who come across the problem are likely to pop up on the forum or over here…

I've also noticed that reaper got some bugs in the current version - time selections going out-of-sync with the grid, amongst others. At first, I spent some time trying to figure whether it was an rk-issue (since it breaks BigItem movements in the TCP), until I saw people mentioning similar problems on Reaper's pre-release forum. From what it looks like, Cockos is working on a release with bug-fixes for early July.

**Comment by molleweide** [comment]
Yeah ill try the kmap and get back. Ig if it works to export that keymap and import it with correct shift keys then this only had to be done once. Hmmm.

**Comment by molleweide** [comment]
We should find the version manager and figure out which versions are best for rk

**Comment by molleweide** [comment]
> This might be a linux-only issue, or because I don't use a qwerty layout, or whatever. I don't know if it's worth running in circles about: most users who come across the problem are likely to pop up on the forum or over here…

No its both linux and macos. Same issue on intel and m1.

And the keyboard layout is not the issue either. Both i and gwatcha are using super wierd custom keyboards and layouts and it used to work fine.
Qmk/kmonad,etc..

**Comment by molleweide** [comment]
Oh wait. I just realized i have to try one other thing as well. Ill come back to here later

**Comment by molleweide** [comment]
now some ppl in the reaper forum have started replying so hopefully we'll get to the bottom with this.
I haven't yet tried your keymap.

Have you tried exporting your updated keymap and then importing it again to see if it works on your own machine?

**Comment by AntoineBalaine** [comment]
Yes. It works just fine when I swap it for the defaults and then re-import - on both macOS and Linux.

**Comment by molleweide** [comment]
Allright, so I tried importing your keymap `reaper-keys-unix` from the branch you linked and the issue still persists for me.
When re-importing, did you do that on macos or linux?

**Comment by molleweide** [comment]
Here are some docs on how keymaps work

https://mespotin.uber.space/Ultraschall/Reaper-Filetype-Descriptions.html#Reaper-kb.ini

Im getting help from Mespotine in the devs forum.
If we resolve the issue I'll try to rewrite the generator script.

**Comment by molleweide** [comment]
@AntoineBalaine can you please try this keymap on your Linux machine and report back:
https://mespotin.uber.space/stuf/reaper-keys-unix-test.ReaperKeyMap

**Comment by AntoineBalaine** [comment]
I'm using my keymap on both Linux and Macos…
The re-import was on linux, while I was figuring stuff out. On macos, I pulled from my branch and stuff worked right away. 
it's a mystery… 

I'll try Mespotine's key-map tonight and let you know. 
We might wanna run a diff between all of them.

**Comment by molleweide** [comment]
Now I tried using your keymap again and the import worked, as did re-importing my own manual update.

**Comment by molleweide** [comment]
I just figured out where the problem seems to be. You can read the progress on the issue under the forum thread where I tried to document my process.

**Comment by molleweide** [comment]
https://forum.cockos.com/showthread.php?p=2689605#post2689605
