### ISSUE TITLE
Keybindings do not recognize capital letters

### ISSUE THREAD

**Issue by tarakciemre** [gwatcha/reaper-keys#56]
When I use any keybindings that include a capital letter, meaning S-<key>, it captures the capital keys as if they are not capital, so I cannot use the bindings that use capital keybindings. I am using a Ubuntu machine. Is there a known reason for this? Thank you in advance!

**Comment by tarakciemre** [comment]
I realized that the issue just before mine is identical to this one at #55 , so I am closing this issue. For now I may remove the shift bindings by hand, although this will take a long time, but I really want to experiment with this plugin because I believe it will be a game changer. Thank you!

**Comment by AntoineBalaine** [comment]
Hello, you can probably pull the updated bindings from my branch, if you want…
