### ISSUE TITLE
Reaper Keys input latency on a fresh Reaper install

### ISSUE THREAD

**Issue by RyanBlaney** [gwatcha/reaper-keys#61]
I have a very minimal install of Reaper with reaper keys, yet there is about a 1 second delay on every reaper keys action. I'm running the linux version of this script and using the latest version of Reaper. Is there any way to get this latency down? Let me know if I need to provide any more information.

**Comment by myrrc** [comment]
Hey! You can download v2 [here](https://raw.githubusercontent.com/gwatcha/reaper-keys/v2/index.xml) and follow the [instructions]( https://github.com/gwatcha/reaper-keys/blob/21764bf2f83204c76b76aa31f85e23c563cde210/README.md#reporting-performance-issues) to report performance issues.

As for me, around 95% is in gfx.* drawing functions

**Comment by AntoineBalaine** [comment]
Which distro are you running? I used to have the same issue, but it got fixed.

**Comment by myrrc** [comment]
Feel free to reopen this issue if performance is bad in v2.0
