### ISSUE TITLE
Error: rk.lua: attempt to index a nil value

### ISSUE THREAD

**Issue by PowerUser64** [gwatcha/reaper-keys#62]
After installing reaper-keys from reapack, running the installer, and importing the keymap, I'm getting this error when I try pressing any keybinds:

```
rk.lua:1: attempt to index a nil value
```

Did I do something wrong in setup? It might be worth expanding the [installation](https://github.com/gwatcha/reaper-keys?tab=readme-ov-file#installation) section of the readme to include further details on how to get a working install.

**Comment by myrrc** [comment]
I believe there's a bug in my code. Can you provide your OS (Windows, I suppose) and Reaper version?

**Comment by myrrc** [comment]
Also, these things will be helpful
1. Full path to the `reaper-keys` directory
2. Any SCR line from the auto generated key map

**Comment by myrrc** [comment]
It's an index naming issue. I've fixed it in master, but the update is a bit tricky:

1. Delete the current index from Reapack (Extensions > Reapack > Manage repositories), re-add it
2. Re-download extension
3. Launch the installer. Do not import the key map yet.
4. Open action list. Key map > Reset all shortcuts in all sections to default
5. Search for "reaper-keys" in action list. You'll likely find something like this:

install-reaper-keys.lua
reaper-keys <...>/Scripts/Reaper keys/internal
reaper-keys <...>/Scripts/reaper-keys/internal

delete both of the "reaper-keys" scripts (Select > right-click > delete selected ...).

6. Import the keymap

**Comment by PowerUser64** [comment]
Awesome, this fixed it!
