### ISSUE TITLE
Does this repo have new maintainer?

### ISSUE THREAD

**Issue by AntoineBalaine** [gwatcha/reaper-keys#63]
Hello, 

Last I'd heard, reaper-keys couldn't get anymore updates since gwatcha wasn't reachable.

Meanwhile, I've kept a fork with over 150 commits, and I published it on reapack…

If @myrrc is able to merge into main here, would you be open to PRs?
That would be good because @molleweide also maintains a big fork (800+ commits) that could benefit the project.

Some of the things that I could bring over:
- implementing a reapack handle that points to this repo
- typing data using LuaLS
- formatting using LuaLS
- fixes to moving around envelope points using keys
- bunch of enhancements to input midi notes and doing midi editing
- small QOL things here and there

Also, other avenues that could be explored: 

**Relative bar/track numbers:** Sexan's done POCs to create overlays on top of specific window elements. We could probably implement relative bar numbers and relative track numbers. I haven't looked into it since I'm pushing other projects this summer, but I'd be good to know if people are interested.

**Comment by myrrc** [comment]
Hi, yes, I'm the new maintainer.
I'm open to PRs, send them surely.

The bottleneck here is definitely my time, as all changes need to be tested by hand.
I have a demo of a testing facility with `xdotool` but it's not production-ready yet,
so I guess personally I'll focus on it.

Regarding UI overlays I see two main points of interest:
- Passing keys over feedback window (I don't show it normally but when it's shown this must be annoying).
- (Possibly) changing the GUI library. Scythe is unmaintained now, unfortunately. I've looked at Reaper
  toolkit and ReaImGui but both of these seem like a lot of changes I wouldn't want to incorporate into
  v2 PR.
However, feel free to work on a particular topic, looking forward to your updates

**Comment by molleweide** [comment]
@myrrc yeah having to test manually is super annoying

**Comment by AntoineBalaine** [comment]
Ok, my first PR's been opened. 

I'll keep upcoming changes as smaller-sized PRs, for the sake of readability, and to avoid doing a giant change in bulk. 
I'll close this issue.

**Comment by myrrc** [comment]
Thanks, will look at your pr during the week.

**Comment by myrrc** [comment]
Check out the tests/ folder and README in master, now you can write auto tests.
Hope that would speed up the development

**Comment by AntoineBalaine** [comment]
Looking forward to digging into the tests.

I don’t think I’ll be able to look into it this week, though - sorry but other projects are calling my immediate attention.

Thanks for the pointer.
