### ISSUE TITLE
Can't load file: ./reaper-keys/key_scripts/main_j.lua

### ISSUE THREAD

**Issue by AlejandroGomezFrieiro** [gwatcha/reaper-keys#68]
Installed from ReaPack using Reaper v7.0.2 on Linux (Ubuntu Studio), and after that it shows an error window with the error of the issue title.

**Comment by myrrc** [comment]
This file should not exist.
What's reaper-keys version and your OS? Also, can you provide the full traceback
if it's present, not only the first line?
Also, a screenshot with Reaper windows and an error would help.

**Comment by myrrc** [comment]
Also, please post new messages instead of editing old ones, as I don't see updates on the latter.

**Comment by myrrc** [comment]
And (hopefully) the last thing: can you paste address of repository you installed via reapack?

**Comment by AlejandroGomezFrieiro** [comment]
I figured out the issue, I still had some leftover binds from a previous version of the plugin in reaper-kb.ini. I thought I had deleted all traces of an old version of it. After removing it and looking through my .config/REAPER folder to make sure there is nothing, this error does not show up again.
