### ISSUE TITLE
Doesn't seem to work, no new key bindings

### ISSUE THREAD

**Issue by David-Else** [gwatcha/reaper-keys#69]
I might just being ignorant about Reaper and reapak. I added this repo for the first time and and installed the v2.0 alpha extension, I now have:

![image](https://github.com/gwatcha/reaper-keys/assets/12832280/304d6b56-493c-4729-8e83-042acd191b24)

Nothing happens, there are no new keys. I found an action and ran it, but that makes no difference:

![image](https://github.com/gwatcha/reaper-keys/assets/12832280/99504cfc-01eb-4572-b0c1-d922700738b0)

What am I missing? Thanks!

**Comment by myrrc** [comment]
You need to press the "Key map..." button (your second image) and import the key map (as said in the popup window).

**Comment by David-Else** [comment]
Thank you! I found [this thread](https://forum.cockos.com/showthread.php?p=2405015#post2405015), and there are many explanations that would greatly benefit users by being included in this repository's README.

I am not sure if I am ready to wipe all my current bindings, but I will revisit this extension soon. For now, I will close this issue.
