### ISSUE TITLE
mac: multiple symbols seem NOT to be working

### ISSUE THREAD

**Issue by molleweide** [gwatcha/reaper-keys#8]
eg.
select -> lastItemEnd
s$
$ sign becomes undefined

**Comment by molleweide** [comment]
f

**Comment by gwatcha** [comment]
Does the dollar sign appear in the action list like so?

![image](https://user-images.githubusercontent.com/31526638/83040945-bd995280-9ff4-11ea-84a1-badc55052067.png)

**Comment by molleweide** [comment]
I'll make sure to check these things before I post next time.
It doesn'g seem to have been assigned.

Before:
`SCR 4 0 reaper_keys_main_$ "[reaper-keys] [key_press] [$]" ./reaper-keys/key_scripts/main_dollar.lua`
After:
`SCR 4 0 reaper_keys_main_$ "[reaper-keys] [key_press] [$]" ./reaper-keys/key_scripts/main_dollar.lua KEY 0 36 _reaper_keys_main_$ 0`

Also, it said that the key was already bound.

**Comment by gwatcha** [comment]
Alright, I think I fixed it  with this commit, 3d67ec4a9e8f7b9203f9421dcace643d8ca6bcd1
Try it out and let me know if it works now.

**Comment by elgiovanno** [comment]
This is fixed for me. Thanks for this amazing reaper script.

**Comment by gwatcha** [comment]
Cool! No problem :)

**Comment by molleweide** [comment]
For me I see that these symbols don' work:
@!#^%&
Can't load file: ./reaper-keys/key*scripts/main*(S-4).lua ...
